"""
run.py
======
Entry point for the AutoGen conversational multi-agent financial analyst.

Usage:
    python -m src.autogen.run

Architecture: conversational agents with code execution (see the
chapter's "Implementation 3: AutoGen (conversational multi-agent)"
section). AutoGen uses conversation as the coordination mechanism — no
explicit handoffs or shared state objects. The assistant generates
Python code, the code_executor runs it, and they iterate until the
task is complete.
"""

import os
import sys
import tempfile

from autogen import AssistantAgent, UserProxyAgent
from autogen.coding import LocalCommandLineCodeExecutor

# The executor runs generated code with whatever `python` is first on
# the PATH, which is not necessarily this interpreter (pyenv shims are
# a classic trap). Prepend this interpreter's directory so the
# generated code runs in the same environment as this script.
os.environ["PATH"] = (
    os.path.dirname(sys.executable) + os.pathsep + os.environ["PATH"]
)

# ---------------------------------------------------------------------------
# Configuration
# ---------------------------------------------------------------------------

config_list = [
    {
        "model": "gpt-4o",
        "api_key": os.getenv("OPENAI_API_KEY"),
    }
]

llm_config = {
    "config_list": config_list,
    "cache_seed": 42,  # Enables caching for reproducibility
}


def run_analysis(query: str) -> dict:
    """Run a two-agent conversation for financial analysis."""

    # Create a temporary directory for code execution
    work_dir = tempfile.mkdtemp()

    # Code executor — runs Python code generated by the assistant
    executor = LocalCommandLineCodeExecutor(
        timeout=60,
        work_dir=work_dir,
    )

    # Assistant agent — LLM-powered, generates code and analysis
    assistant = AssistantAgent(
        name="assistant",
        llm_config=llm_config,
        system_message=(
            "You are a financial analyst assistant. When asked to "
            "analyze a company, write Python code using yfinance "
            "to fetch financial data and compute key metrics. "
            "Present results in a clear, structured format. "
            "Save any plots to PNG files instead of calling "
            "plt.show(). After you have seen the execution results "
            "and written your final analysis, end that final message "
            "with TERMINATE. Never write TERMINATE in a message that "
            "contains code."
        ),
    )

    # Code executor agent — runs code, returns results
    code_executor = UserProxyAgent(
        name="code_executor",
        human_input_mode="NEVER",
        code_execution_config={"executor": executor},
        llm_config=False,
        is_termination_msg=lambda msg: (
            msg.get("content", "")
            and "TERMINATE" in msg.get("content", "")
        ),
    )

    # Start the conversation
    chat_result = code_executor.initiate_chat(
        assistant,
        message=query,
        max_turns=5,
    )

    # Print cost tracking
    print(f"\n{'=' * 50}")
    print("COST SUMMARY:")
    print(f"{'=' * 50}")
    print(chat_result.cost)

    return {
        "chat_history": chat_result.chat_history,
        "cost": chat_result.cost,
        "summary": chat_result.summary,
    }


if __name__ == "__main__":
    query = (
        sys.argv[1]
        if len(sys.argv) > 1
        else "What is the current price and key financial metrics "
        "of NVIDIA? Plot the stock price over the last 6 months."
    )
    print(f"\nQuery: {query}\n")
    result = run_analysis(query)
    print(f"\n{'=' * 50}")
    print("SUMMARY:")
    print(f"{'=' * 50}")
    print(result["summary"])
